name: CLI Docker

on:
  push:
    branches:
      - "*.staging"

# cancel in-progress runs on new commits to same PR (gitub.event.number)
concurrency:
  group: vercel-deploy-${{ github.workflow }}-${{ github.event.number || github.sha }}
  cancel-in-progress: true

permissions:
  contents: read # to fetch code (actions/checkout)
  statuses: write # This is required for the GitHub Script createCommitStatus to work
  packages: write

jobs:
  build:
    environment:
      name: "staging"

    timeout-minutes: 20

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{ github.event.pull_request.head.sha || github.sha }} # HEAD commit instead of merge commit

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

          # username: ${{ secrets.DOCKERHUB_USER }}
          # password: ${{ secrets.DOCKERHUB_TOKEN }}

      # To be able to pull image by branh name, sha, short sha and tag
      # i.e. olegisonen/webstudio:hello.staging
      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v5
        with:
          # TODO: create team someday on dockerhub
          images: |
            ghcr.io/webstudio-is/webstudio
          tags: |
            type=sha,format=long
            type=sha,format=short
            type=ref,event=branch
            type=ref,event=tag

      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./devops/cli/Dockerfile
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
