name: CSS Data
on:
  push:
    paths:
      - "packages/css-data/**/*"
      - ".github/workflows/css-data.yml"
      - ".github/actions/publish/action.yaml"
    branches:    
      - main
jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/publish
        with:
          workdir: ./packages/css-data
          filter: "@webstudio-is/css-data"
          token: ${{ secrets.NPM_TOKEN }}
