name: CSS Engine
on:
  push:
    paths:
      - "packages/css-engine/**/*"
      - ".github/workflows/css-engine.yml"
      - ".github/actions/publish/action.yaml"
    branches:    
      - main
jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/publish
        with:
          workdir: ./packages/css-engine
          filter: "@webstudio-is/css-engine"
          token: ${{ secrets.NPM_TOKEN }}
