name: Design System Publish
on:
  push:
    paths:
      - "packages/design-system/**/*"
      - ".github/workflows/design-system.yml"
      - ".github/actions/publish/action.yaml"
jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/publish
        with:
          package: "./packages/design-system/package.json"
          token: ${{ secrets.NPM_TOKEN }}
