name: HTTP Client Publish
on:
  push:
    paths:
      - "packages/http-client/**/*"
      - ".github/workflows/http-client.yml"
      - ".github/actions/publish/action.yaml"
jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/publish
        with:
          package: "./packages/http-client/package.json"
          token: ${{ secrets.NPM_TOKEN }}
