name: HTTP API Publish
on:
  push:
    paths:
      - "packages/http-api/**/*"
      - ".github/workflows/http-api.yml"
      - ".github/actions/publish/action.yaml"
jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/publish
        with:
          package: "./packages/http-api/package.json"
          token: ${{ secrets.NPM_TOKEN }}
