name: Icons Publish
on:
  push:
    paths:
      - "packages/icons/**/*"
      - ".github/workflows/icons-publish.yml"
      - ".github/actions/publish/action.yaml"
jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/publish
        with:
          package: "./packages/icons/package.json"
          token: ${{ secrets.NPM_TOKEN }}
