name: Icons
on:
  push:
    paths:
      - "packages/icons/**/*"
      - ".github/workflows/package-tests.yml"
      - ".github/actions/publish-test/action.yaml"
    branches:    
      - main
jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/publish
        with:
          workdir: ./packages/icons
          filter: "@webstudio-is/icons"
          token: ${{ secrets.NPM_TOKEN }}
