name: Icons
on:
  push:
    branches:    
      - main
jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/publish
        with:
          workdir: ./packages/icons
          filter: "@webstudio-is/icons"
          token: ${{ secrets.NPM_TOKEN }}
