name: Jest Config
on:
  push:
    paths:
      - "packages/jest-config/**/*"
      - ".github/workflows/package-tests.yml"
      - ".github/actions/publish-test/action.yaml"
    branches:    
      - main
jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/publish
        with:
          skip-build: true
          workdir: ./packages/jest-config
          filter: "@webstudio-is/jest-config"
          token: ${{ secrets.NPM_TOKEN }}
