name: Main workflow
on: [push]
jobs:
  checks:
    env:
      NODE_ENV: test
      DATABASE_URL: postgres://
      AUTH_SECRET: test
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        node: ["14.x", "16.x"]
        os: [ubuntu-latest]
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2
        
      - name: Setup Node.js ${{ matrix.node }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node }}
          cache: "yarn"
          
      - run: yarn install --frozen-lockfile
      - run: yarn prisma generate
      - run: yarn build
      - run: yarn checks
