name: Main workflow
on: [push]
jobs:
  checks:
    env:
      NODE_ENV: test
      DATABASE_URL: postgres://
      AUTH_SECRET: test
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        node: ["14.x", "16.x"]
        os: [ubuntu-latest]
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2
      - run: yarn install
      - run: yarn prisma generate
      - run: yarn build
      - run: yarn checks
