name: SDK publish
on:
  push:
    paths:
      - "packages/react-sdk/**/*"
      - ".github/workflows/react-sdk-publish.yml"
      - ".github/workflows/publish/action.yaml"
jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/publish
        with:
          package: "./packages/react-sdk/package.json"
          token: ${{ secrets.NPM_TOKEN }}
