name: Tsconfig Publish
on:
  push:
    paths:
      - "packages/tsconfig/**/*"
      - ".github/workflows/tsconfig-publish.yml"
jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/publish
        with:
          package: "./packages/tsconfig/package.json"
          token: ${{ secrets.NPM_TOKEN }}
