on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Node
        uses: actions/setup-node@v2
        with:
          node-version: 16.x
          cache: 'npm'

      - name: Install dependencies
        run: yarn install --frozen-lockfile --ignore-scripts

      - name: Build Storybook for Design System
        run: yarn storybook:ds:build

      - name: Lost Pixel
        uses: lost-pixel/lost-pixel@v2.23.0
        env:
          S3_ACCESS_KEY: ${{ secrets.S3_ACCESS_KEY }}
          S3_SECRET_KEY: ${{ secrets.S3_SECRET_KEY }}
          LOST_PIXEL_CONFIG_DIR: packages/design-system
