on: [push]

jobs:
  build:
    timeout-minutes: 20

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/ci-setup

      - name: Build Storybook for Design System
        run: yarn storybook:ds:build

      - name: Lost Pixel
        uses: lost-pixel/lost-pixel@v2.23.0
        env:
          S3_ACCESS_KEY: ${{ secrets.S3_ACCESS_KEY }}
          S3_SECRET_KEY: ${{ secrets.S3_SECRET_KEY }}
          LOST_PIXEL_CONFIG_DIR: packages/design-system
