name: Main workflow
on: [push]
jobs:
  checks:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        node: ["14.x", "16.x"]
        os: [ubuntu-latest]
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2

      # - name: Install deps and build (with cache)
      #   uses: bahmutov/npm-install@v1
      - run: yarn install

      - name: Next.js cache
        uses: actions/cache@v2
        with:
          path: ${{ github.workspace }}/.next/cache
          key: ${{ runner.os }}-${{ runner.node }}-${{ hashFiles('**/yarn.lock') }}-nextjs

      - run: yarn typecheck
      - run: yarn test
      - run: yarn build
